theme: jekyll-theme-cayman
<!DOCTYPE html>
<html>
		<body> 
		<div class="container">
		  <img src="image.jpg" alt="chinna" width="75" height="100">
		  <div class="topleft"></div>
		</div>
		<div id="header">
			<h1 class="hover">Welcome to Awais Hussain Page </h1>
			<style>	h1 {  text-align: center;}</style>
			<!--<p style="color:blue;"> id="name">Awais Hussain | Mail:2020mt93185@wilp.bits-pilani.ac.in| Mobile:+91 9686020007 <p/>-->
			<!--<p style="color:blue;"> Contact </p>-->
			<h2>Contact</h2>
			<p style="color:blue;">Name    : Awais Hussain</p>  
			<p style="color:blue;">BITS ID : 2020mt93185@wilp.bits-pilani.ac.in</p>
			<p style="color:blue;">Mobile  : +91 9686020007 </p> 
			
			<!--<a href="mailto:2020mt93185@wilp.bits-pilani.ac.in><p id="email">2020mt93185@wilp.bits-pilani.ac.in</p></a>-->
			<!---<p>or</p>-->
			<!--<a href="mailto:office-admin@outlook.com><p id="email">envision@extremenetwrks.com</p></a>-->
			<!---<body style="background-color: #CCEEFF;">-->

		</div>
		<h2>About Me</h2>
			<p>A Passionate Software Engineer with almost 2 years of experience and focused in enhancing technical paths for stakeholder's business. 
			Graduated in April 2018 from GITAM UNIVERSITY which is a research UNIVERSITY in TECHNOLOGY and MANAGEMENT recognized under UGC and NAAC certified with A+ grade.
            I am currently working as an EDI Analyst with a professional knowledge of 2 years. I am motivated and well organized with proven expertise in Technical industry. 
			I play the role of good team member, team leader and skilled in identifying and resolving technical issues</p>
		
		
			<h2>Education</h2>
			<table border="1"> 
				<tr>
					<th>Year</th>
					<th>College/Univery</th>
				</tr>
				<tr>
					<td>2021</td>
					<td>M.Tech in software Engineering from Birla Institute of Technology & Science, Pilani (Pursuing)</td>
					
				</tr>
				<tr>
					<td>2018</td>
					<td>B.Tech. Computer Science Engineering from GITAM Deemed to be University Bengaluru</td>
				</tr>
				</table>
		
		<h2>Work Experience</h2>
			<table border="1"> 
				<tr>
					<th>Year</th>
					<th>Role/Organization</th>
				</tr>
				<tr>
					<td>2019 - Present</td>
					<td>Software Engineer, HCL Technologies Limited, Bangalore </td>
				</tr>
				</table>
			<h2>Project works</h2>
		<h2>Project #1 - US Based (12/2018 – 10/2019)</h2>
			<p>
			 <li>Worked under FORGEROCK TECHNOLOGY,IAM and OPENDJ.</li>
			 <li>Working knowledge in solving SERVICE NOW INCIDENTS.</li>
			 <li>•	Good perception of IAM concepts and worked on preparing QA,QP report</li></p>
	
		<h2>Project #2 - US Based Client PBGH(Premier Brands Group Holdings LLC)  (10/2019 to Present)</h2>
		<p> 
	   	 <li>Supporting US client and their vendors in EDI –Supply Chain Management.</li>
			<li>Strong knowledge in ANSIX12, EDIFACT</li>
			<li>EDI Transactions – 850, 855, 860, 856, 810, 870 and 997.</li>
			<li>Good understanding of communication protocols AS2, FTP, HTTP and VAN</li>
			<li>Good knowledge in Enveloping & Structure</li>
			<li>Good knowledge and understanding the business domain, EDI mapping and its involved technologies..</li>
			<li>Good knowledge in SAP-ERP ECC 5.0 Production and few transactions like VA03, VF03, VT03, VT70 and WE05.</li>
			<li>Managed EDI queries received from customers (internal departments or trading partners) or automatic failure notification from EDI tool to EDI Group-mail box.</li>
			<li>Segregate and analyze EDI issues on X12 EDI document mainly on 850, 860, 856, and 810</li>
			<li>Need to find out the issues from X12 document and analyze the errors to be fixed. Identify and assigning issues that need support from various project stakeholders.</li>
			<li>Providing technical support and actively involved in resolving questions from stakeholders.</li>
		    <li>Restarting a failed Business Process, Outbound FTP in SI.</li>
			<li>Processing Inbound FTP in SI.</li>
			<li>Excellent communication skill to interact directly with the Customer, Business Analyst team and Technical team.</li>
			<li>Responsible for the Weekly Status Report and Monthly KPI Reports to be provided to client.</li></p>
		<p>Bangalore, Karnata , 560087<p>

		<h2>Things I like to do</h2>
			<ul>
				<li>Watching TV Shows</li>
				<li>Football</li>
				<li> Exploring New Places</li>
			</ul>
		
			<h2>Favorite TV Shows</h2>
			<ul>
				<li>Friends</li>
				<li>Sherlock</li>
				<li>Game Of Thrones</li>
				<li>Avengers</li>
				<li>Dark Knight</li>
			</ul>
			<h2>Favorite Places by City</h2>
			<table border="1"> 
				<tr>
					<th>State</th>
					<th>Place</th>
				</tr>
				<tr>
					<td>Karnatak</td>
					<td>Coorg</td>
					
				</tr>
				<tr>
					<td>GOA</td>
					<td>North Goa </td>
				</tr>
				<tr>
					<td>UK</td>
					<td>Manchester</td>
				<tr>
			</table>
				
	</body>
</html>
